DROP TABLE devices IF EXISTS;
CREATE TABLE devices
(
    id              bigint generated by default as identity,
    create_at       timestamp,
    update_at       timestamp,
    name            varchar(255),
    ssh_username    varchar(255),
    ssh_host        varchar(255),
    ssh_port        int,
    ssh_public_key  varchar(1024),
    primary key (id)
);


DROP TABLE commands IF EXISTS;
CREATE TABLE commands
(
    id          bigint generated by default as identity,
    create_at   timestamp,
    update_at   timestamp,
    type        varchar(255) not null,
    result      longvarchar(2048),
    device_id   varchar(255) references devices,
    script      varchar(255),
    body        varchar(255),
    url         varchar(255),
    method      varchar(255),
    primary key (id)
);
